import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {makeBook} from './book-model.mjs?v=3';
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.setClearColor(0x353638,1);
renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure=1.0;
document.querySelector('main').append(renderer.domElement);
const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(35,1,1,2000);
camera.up.set(0,0,1);
const controls=new OrbitControls(camera,renderer.domElement);
controls.enableDamping=true;controls.dampingFactor=.09;
controls.minDistance=250;controls.maxDistance=1000;
controls.target.set(0,0,10);
const data=makeBook(),geo=new THREE.BufferGeometry();
geo.setAttribute('position',new THREE.Float32BufferAttribute(data.positions,3));
geo.setAttribute('color',new THREE.Float32BufferAttribute(data.colors,3));
geo.setIndex(data.indices);geo.computeVertexNormals();geo.computeBoundingSphere();
const book=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0xffffff,vertexColors:true,roughness:.92,metalness:0}));
book.name='Open book — single watertight mesh';book.castShadow=true;book.receiveShadow=true;scene.add(book);
scene.add(new THREE.HemisphereLight(0xffffff,0x9597a1,.65));
const key=new THREE.DirectionalLight(0xffffff,2.8);key.position.set(-160,-80,260);key.castShadow=true;
key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-220,right:220,top:230,bottom:-230,near:1,far:800});
key.shadow.bias=-.00015;key.shadow.normalBias=.08;scene.add(key);
const fill=new THREE.DirectionalLight(0xe9efff,.45);fill.position.set(180,130,200);scene.add(fill);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(2000,2000),new THREE.ShadowMaterial({opacity:.25}));floor.position.z=-2.1;floor.receiveShadow=true;scene.add(floor);
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}
function reset(){
  const halfV=THREE.MathUtils.degToRad(camera.fov/2);
  const halfH=Math.atan(Math.tan(halfV)*camera.aspect);
  const distance=geo.boundingSphere.radius/Math.sin(Math.min(halfV,halfH))*1.07;
  const direction=new THREE.Vector3(-.52,-.90,.84).normalize();
  controls.target.set(0,0,21);
  camera.position.copy(direction.multiplyScalar(distance).add(controls.target));
  controls.update();
}
addEventListener('resize',resize);resize();reset();
document.querySelector('#reset').onclick=reset;
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});
